/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bowling_ball.glb 
Author: A_dub (https://sketchfab.com/A_dub)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bowling-ball-5377e2fa1d904a8c919341c6b3e0f182
Title: Bowling Ball
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Bowling_Ball(props) {
  const { nodes, materials } = useGLTF('/bowling_ball.glb')
  return (
    <RigidBody mass={1000} friction={0} // Low friction for slippery motion
    restitution={0.5}  >

    <group {...props} dispose={null}>
      <group position={[0,1.5,0]} rotation={[-Math.PI / 2, 0, 0]} scale={30}>
        <mesh geometry={nodes.Bowling_Ball_Bowling_Ball_0.geometry} material={materials.Bowling_Ball} />
        <mesh geometry={nodes.Bowling_Ball_Hole_Colour_0.geometry} material={materials.Hole_Colour} />
      </group>
    </group>
    </RigidBody>

  )
}

useGLTF.preload('/bowling_ball.glb')
