/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 GitHub.glb 
Author: pissang (https://sketchfab.com/YiChen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/github-octocat-c8a4795ce3fe4b21a4c40895cb9cb6a5
Title: GitHub Octocat
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function GitHub(props) {
  const { nodes, materials } = useGLTF('/GitHub.glb')
  return (
    <RigidBody>

    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} position={[0.004, 9.995, 0.636]} scale={0.05} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_1} position={[0.002, 9.997, 1.487]} scale={0.05} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_2} position={[-0.002, 9.994, 1.813]} scale={0.05} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_3} position={[-0.002, 9.988, 1.8]} scale={0.05} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_4} position={[-0.001, 9.996, 1.81]} scale={0.05} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_5} position={[0.012, 10.002, 1.755]} scale={0.05} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.material_6} position={[0, 9.995, 1.325]} scale={0.05} />
    </group>
    </RigidBody>

  )
}

useGLTF.preload('/GitHub.glb')
