/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LinkedIn.glb 
Author: studiometa (https://sketchfab.com/studiometa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/linkedin-3d-c62b9be6edfc46b4a887c2a2ff0148d8
Title: Linkedin 3D
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function LinkedIn(props) {
  const { nodes, materials } = useGLTF('/LinkedIn.glb')
  return (
    <RigidBody>

    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes['Objeto_1_Tinta_(1)_0'].geometry} material={materials.Tinta_1} />
        <mesh geometry={nodes['Objeto_2_Tinta_(3)_0'].geometry} material={materials.Tinta_3} />
        <mesh geometry={nodes['Objeto_3_Tinta_(3)_0'].geometry} material={materials.Tinta_3} />
        <mesh geometry={nodes['Objeto_4_Tinta_(3)_0'].geometry} material={materials.Tinta_3} />
      </group>
    </group>
    </RigidBody>

  )
}

useGLTF.preload('/LinkedIn.glb')
